"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Mock3__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var Mock3__factory_1 = require("./Mock3__factory");
Object.defineProperty(exports, "Mock3__factory", { enumerable: true, get: function () { return Mock3__factory_1.Mock3__factory; } });
