/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mockContractSol from "./MockContract.sol";
export * as mockContract2Sol from "./MockContract2.sol";
export * as mockContract3Sol from "./MockContract3.sol";
