"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Mock2__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var Mock2__factory_1 = require("./Mock2__factory");
Object.defineProperty(exports, "Mock2__factory", { enumerable: true, get: function () { return Mock2__factory_1.Mock2__factory; } });
