"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Proxy__factory = exports.IProxy__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IProxy__factory_1 = require("./IProxy__factory");
Object.defineProperty(exports, "IProxy__factory", { enumerable: true, get: function () { return IProxy__factory_1.IProxy__factory; } });
var Proxy__factory_1 = require("./Proxy__factory");
Object.defineProperty(exports, "Proxy__factory", { enumerable: true, get: function () { return Proxy__factory_1.Proxy__factory; } });
