"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Mock__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var Mock__factory_1 = require("./Mock__factory");
Object.defineProperty(exports, "Mock__factory", { enumerable: true, get: function () { return Mock__factory_1.Mock__factory; } });
