/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockContractSol from "./MockContract.sol";
export type { mockContractSol };
import type * as mockContract2Sol from "./MockContract2.sol";
export type { mockContract2Sol };
import type * as mockContract3Sol from "./MockContract3.sol";
export type { mockContract3Sol };
